// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7rpjMxaZ2VmuoqOcdrI4v3Ca3sg6CW1Q',
    appId: '1:281458418960:web:ee97bfa1b092a746403195',
    messagingSenderId: '281458418960',
    projectId: 'malawi-aip-tracker',
    authDomain: 'malawi-aip-tracker.firebaseapp.com',
    storageBucket: 'malawi-aip-tracker.firebasestorage.app',
    measurementId: 'G-L9MPTT3Q8D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8L4tar0TadxFpm2rugVvn-bhIwlolhg',
    appId: '1:281458418960:android:d951422d08309616403195',
    messagingSenderId: '281458418960',
    projectId: 'malawi-aip-tracker',
    storageBucket: 'malawi-aip-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyBaP9dOuwmD2ShrKZNinP1EPu6_Fd4aM',
    appId: '1:281458418960:ios:e409f2ca2174baae403195',
    messagingSenderId: '281458418960',
    projectId: 'malawi-aip-tracker',
    storageBucket: 'malawi-aip-tracker.firebasestorage.app',
    iosBundleId: 'com.example.malawiAipTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyBaP9dOuwmD2ShrKZNinP1EPu6_Fd4aM',
    appId: '1:281458418960:ios:e409f2ca2174baae403195',
    messagingSenderId: '281458418960',
    projectId: 'malawi-aip-tracker',
    storageBucket: 'malawi-aip-tracker.firebasestorage.app',
    iosBundleId: 'com.example.malawiAipTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7rpjMxaZ2VmuoqOcdrI4v3Ca3sg6CW1Q',
    appId: '1:281458418960:web:c4b2acc07c5b8efe403195',
    messagingSenderId: '281458418960',
    projectId: 'malawi-aip-tracker',
    authDomain: 'malawi-aip-tracker.firebaseapp.com',
    storageBucket: 'malawi-aip-tracker.firebasestorage.app',
    measurementId: 'G-T5D3CJ0J8Q',
  );
}
